= Novedades

Las principales novedades de esta versión de _Stratio Cloud Provisioner_ son:

* Incremento de la concurrencia de los controladores Flux en entornos _multi-tenant_.
* Nuevo campo _gitops++_++enabled_ en `ClusterConfig` para omitir el despliegue de componentes gestionados vía GitOps.
* [EKS] Cifrado por defecto para los volúmenes de EBS.
* [GKE] Activación de Workload Identity.
* [GKE] Nuevo campo _additional++_++labels_ en los _worker nodes_ para gestionar etiquetas adicionales en los _node pools_.
* Soporte para la actualización de _cloud-provisioner_, _cluster-operator_ y proveedores en EKS, Azure y GKE.
* Eliminación de _kube-rbac-proxy_ en _cluster-operator_.
* Actualización de Flux a v2.7.5.
* Actualización de Tigera Operator y Calico a la versión 3.30.2.
* Actualización de componentes de AWS: CAPA (v2.9.2), AWS Load Balancer Controller (v1.14.1), Cluster Autoscaler (v1.34.1) y _addons_ de EKS (`aws-ebs-csi-driver`, CoreDNS, `kube-proxy` y `vpc-cni`).
* Actualización de componentes de Azure: CAPZ (v1.21.1), Azure Service Operator (v2.11.0), CSI Azure Disk (v1.33.5), CSI Azure File (v1.34.1), `azure-cloud-controller-manager` y `cloud-node-manager` (v1.34.2).
* Resolución de vulnerabilidades en los componentes de _cloud-provisioner_.
