apiVersion: dns.gcp.upbound.io/v1beta1
kind: ManagedZone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/managedzoneiammember
  labels:
    testing.upbound.io/example-name: managed-zone
  name: private-managed-zone
spec:
  providerConfigRef:
    name: external-dns-provider
  forProvider:
    description: Private DNS zone for external-dns
    //IMPORTANTE, acabado en "."
    dnsName: lreciodomain.ext.
    visibility: private
---
apiVersion: dns.gcp.upbound.io/v1beta1
kind: ManagedZone
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1beta1/managedzoneiammember
  labels:
    testing.upbound.io/example-name: managed-zone
  name: managed-zone
spec:
  providerConfigRef:
    name: external-dns-provider
  forProvider:
    description: Public DNS zone for external-dns
    //IMPORTANTE, acabado en "."
    dnsName: lreciodomain.ext.
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  labels:
    keos.stratio.com/sa-name: sa-external-dns-lrecio-gcp-2
  name: sa-external-dns-lrecio-gcp-2
spec:
  providerConfigRef:
    name: external-dns-provider
  forProvider:
    displayName: Service Account for external-dns in cluster lrecio-gcp-2
    createIgnoreAlreadyExists: true
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountKey
metadata:
  labels:
    keos.stratio.com/sa-key-name: sa-key-external-dns-lrecio-gcp-2
  name: sa-key-external-dns-lrecio-gcp-2
spec:
  providerConfigRef:
    name: external-dns-provider
  writeConnectionSecretToRef:
    name: sa-key-external-dns-lrecio-gcp-2-secret
    namespace: crossplane-system
  forProvider:
    serviceAccountIdSelector:
      matchLabels:
        keos.stratio.com/sa-name: sa-external-dns-lrecio-gcp-2
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/projectiammember
  labels:
    testing.upbound.io/example-name: project-iam-member
  name: project-iam-member
spec:
  providerConfigRef:
    name: external-dns-provider
  forProvider:
    member: serviceAccount:sa-external-dns-lrecio-gcp-2@clusterapi-369611.iam.gserviceaccount.com
    project: clusterapi-369611
    role: roles/dns.admin
