= Gestión de credenciales

Actualmente, para la comunicación con los proveedores _cloud_, los _controllers_ almacenan en el _cluster_ las credenciales de la identidad utilizada en la instalación.

En la primera ejecución, las credenciales para el aprovisionamiento en el proveedor _cloud_ se indican en el apartado _credentials_ del fichero _manifest_ que define el objeto _KeosCluster_.

Estos secretos se cifran con una _passphrase_ solicitada desde en el aprovisionamiento en el fichero _secrets.yml_, eliminándose todo el apartado de credenciales del descriptor. En posteriores ejecuciones, simplemente se solicita la _passphrase_ para descifrar el fichero de secretos, de donde se leen las credenciales.


== Renovación de credenciales

En el caso de que necesite renovar alguna de estas credenciales es necesario realizar las operativas que se detallan a continuación. Estas operativas varían en función del _cloud_ donde se haya desplegado _Stratio KEOS_.

=== EKS

TODO

=== Azure no gestionado

TODO

=== GKE

. Cambio de las credenciales referenciadas en _cluster-operator_:

* Obtenemos los _values_ del _chart_ de _cluster-operator_:

[source,console]
----
helm get values -n kube-system cluster-operator -a > /tmp/cluster-operator-current-values.yml
----

* Modificamos el _value_ `credentialsBase64` el fichero `/tmp/cluster-operator-current-values.yml`.

* Actualizamos el _chart_ de _cluster-operator_ haciendo uso del fichero de _values_ modificado anteriormente:

[source,console]
----
helm upgrade --reuse-values -f /tmp/cluster-operator-modified-values.yml -n kube-system <cluster_operator_chart_url> --version <cluster_operator_chart_version>
----

* Revisamos el contenido del secreto de _Kubernetes_ de nombre `keoscluster-settings` en el _namespace_ `kube-system`.

* Reiniciamos el _deployment_ de nombre `keoscluster-controller-manager` en el _namespace_ `kube-system`.

. Cambio de las credenciales referenciadas en los componentes de _capg_:

* Modificamos el secreto de _Kubernetes_ nombre `capg-manager-bootstrap-credentials` en el _namespace_ `capg-system` dejándolo alineado con el secreto de _Kubernetes_ de nombre `keoscluster-settings` en el _namespace_ `kube-system`.

* Reiniciamos el _deployment_ de nombre `capg-controller-manager` en el _namespace_ `capg-system`.

. Cambio del contenido del fichero `secrets.yml`:

* Seguimos el procedimiento definido en la xref:stratio-keos:operations-guide:cluster-operation/credentials.adoc[documentación de gestión de credenciales en _Stratio KEOS_].
