apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: {{ repository_name }}
  namespace: kube-system
spec:
  url: {{ repository_url }}
  interval: {{ interval }}
  type: {{ schema }}
  provider: {{ provider }}
{%- if repository_name == "keos" %}
  secretRef:
    name: {{ repository_name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ repository_name }}
  namespace: kube-system
stringData:
  username: {{ username }}
  password: {{ password }}
{%- endif %}
