apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ ReleaseName }}
  namespace: {{ ChartNamespace }}
spec:
  releaseName: {{ ReleaseName }}
  chart:
    spec:
      chart: {{ ChartName }}
      version: "{{ ChartVersion }}"
      sourceRef:
        kind: HelmRepository
        name: {{ ChartRepoRef }}
        namespace: kube-system
      interval: {{ HelmReleaseSourceInterval }}
  interval: {{ HelmReleaseInterval }}
  install:
    crds: CreateReplace
    remediation:
      retries: {{ HelmReleaseRetries }}
  upgrade:
    crds: CreateReplace
    remediation:
      retries: {{ HelmReleaseRetries }}
      remediateLastFailure: true
    force: false
  valuesFrom:
    - kind: ConfigMap
      name: 00-{{ ReleaseName }}-helm-chart-default-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: 02-{{ ReleaseName }}-helm-chart-override-values
      valuesKey: values.yaml