---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: aws-node
    k8s-app: aws-node
  name: aws-node-annotate-pod-ip
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: aws-node
  name: aws-node-annotate-pod-ip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-node-annotate-pod-ip
subjects:
- kind: ServiceAccount
  name: aws-node
  namespace: kube-system