apiVersion:  apiextensions.crossplane.io/v1 
kind:  CompositeResourceDefinition 
metadata: 
  name:  xiamconfigs.configs.stratio.io 
spec: 
  group: configs.stratio.io
  names: 
    kind:  xIamConfig 
    plural:  xiamconfigs
  versions: 
    -  name:  v1alpha1 
       served:  true 
       referenceable:  true 
       schema: 
         openAPIV3Schema: 
           type:  object 
           properties: 
            spec: 
                type:  object
                properties:
                  providerConfigName:
                    type: string
                    default: "default"
                  clusterName:
                    type: string
                  # adoption:
                  #   type: boolean
                  #   default: false
                  # externalNames:
                  #   type: object
                  #   optional: true
                  #   properties:
                  #     user:
                  #       type: string
                  #     policy:
                  #       type: string
                  #     userPolicyAttachment:
                  #       type: string
                  #     accessKey:
                  #       type: string
            status:
                type: object
                properties:
                  policy:
                    type: object
                    properties:
                      arn: 
                        type: string
                      externalName: 
                        type: string
                  user:
                    type: object
                    properties:
                      arn:
                        type: string
                      uniqueId:
                        type: string
                      externalName: 
                        type: string
                  userPolicyAttachment:
                    type: object
                    properties:
                      id:
                        type: string
                      policyArn:
                        type: string
                      user:
                        type: string
                      externalName: 
                        type: string
                  accessKey:
                    type: object
                    properties:
                      externalName: 
                        type: string
                      user:
                        type: string
                      connectionSecret:
                        type: object
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
---