apiVersion:  apiextensions.crossplane.io/v1 
kind:  CompositeResourceDefinition 
metadata: 
  name:  xawszonesconfigs.configs.stratio.io 
spec: 
  group: configs.stratio.io
  names: 
    kind:  xAWSZonesConfig 
    plural:  xawszonesconfigs
  versions: 
    -  name:  v1alpha1 
       served:  true 
       referenceable:  true 
       schema: 
         openAPIV3Schema: 
           type:  object 
           properties: 
            spec: 
                type:  object
                properties:
                  region:
                    type: string
                  vpcId:
                    type: string
                  externalDomain:
                    type: string
                  clusterName:
                    type: string
                  accountId:
                    type: integer
                    format: int64
                  oidcProviderId:
                    type: string
                  providerConfigName:
                    type: string
                    default: "default"
            status:
                type: object
                properties:
                  hostedZones:
                    type: object
                    properties:
                      publicZoneArn: 
                        type: string
                      privateZoneArn: 
                        type: string
                  policy:
                    type: object
                    properties:
                      arn: 
                        type: string
                  role:
                    type: object
                    properties:
                      arn:
                        type: string
                      uniqueId:
                        type: string
                  rolePolicyAttachment:
                    type: object
                    properties:
                      id:
                        type: string
                      policyArn:
                        type: string
                      role:
                        type: string
---