= Credential Management

To allow the controllers to communicate with cloud providers, they store the identity credentials used during the installation in the cluster.

During the first run, the required credentials are specified in the 'credentials' section of the manifest file that defines the _KeosCluster_ object.

These credentials are encrypted with a passphrase introduced during provisioning and are stored in the _secrets.yml_ file, being removed from the descriptor. In subsequent runs, you only need to enter the passphrase to decrypt the file and access the credentials.

== Credential Renewal

If you need to renew any credential, follow the steps according to the cloud provider where _Stratio KEOS_ is deployed.

=== EKS

. Update the credentials in _cluster-operator_:
+
* Fetch the values of the _cluster-operator_ chart:
+
[source,console]
----
helm get values -n kube-system cluster-operator -a > /tmp/cluster-operator-current-values.yml
----
+
* Modify the `credentialsBase64` value in the file /tmp/cluster-operator-current-values.yml.
+
* Apply the changes to the chart:
+
[source,console]
----
helm upgrade --reuse-values -f /tmp/cluster-operator-modified-values.yml -n kube-system <cluster_operator_chart_url> --version <cluster_operator_chart_version>
----
+
* Check the `keoscluster-settings` secret in the `kube-system` namespace.
+
* Restart the `keoscluster-controller-manager` deployment in `kube-system`.

. Update the credentials in the capa components:
+
* Modify the `capa-manager-bootstrap-credentials` secret in `capa-system`, aligning it with `keoscluster-settings` in `kube-system`.
+
* Restart the `capa-controller-manager` deployment in `capa-system`.

. Update the _secrets.yml_ file:
+
* Follow the procedure detailed in the xref:stratio-keos:operations-guide:cluster-operation/credentials.adoc[_Stratio KEOS_ credential management documentation].

=== Unmanaged Azure

. Update credentials in _cluster-operator_:
+
* Extract the values of the _cluster-operator_ chart:
+
[source,console]
----
helm get values -n kube-system cluster-operator -a > /tmp/cluster-operator-current-values.yml
----
+
* Modify the `secrets.azure` value in the file /tmp/cluster-operator-current-values.yml.
+
* Apply the changes to the chart using the previously modified file:
+
[source,console]
----
helm upgrade --reuse-values -f /tmp/cluster-operator-modified-values.yml -n kube-system <cluster_operator_chart_url> --version <cluster_operator_chart_version>
----
+
* Verify the `keoscluster-settings` secret in the `kube-system` namespace.
+
* Restart the `keoscluster-controller-manager` deployment in `kube-system`.

. Update credentials in the capz components:
+
* Modify the `Azureidentity` object in the `capz-system` namespace to update the `clientID` content.
+
* Modify the associated secret (verifying its name in `Azureidentity`) to update the `clientSecret` content.
+
* Restart the `capz-controller-manager` deployment in `capz-system`.

. Update the _secrets.yml_ file:
+
* Follow the procedure indicated in the xref:stratio-keos:operations-guide:cluster-operation/credentials.adoc[Stratio KEOS credential management documentation].

=== GKE

. Update the credentials in _cluster-operator_:
+
* Extract the values of the chart:
+
[source,console]
----
helm get values -n kube-system cluster-operator -a > /tmp/cluster-operator-current-values.yml
----
+
* Modify the `credentialsBase64` value in the file /tmp/cluster-operator-current-values.yml.
+
* Apply the changes to the chart using the previously modified file:
+
[source,console]
----
helm upgrade --reuse-values -f /tmp/cluster-operator-modified-values.yml -n kube-system <cluster_operator_chart_url> --version <cluster_operator_chart_version>
----
+
* Verify the `keoscluster-settings` secret in the `kube-system` namespace.
+
* Restart the `keoscluster-controller-manager` deployment in `kube-system`.

. Update credentials in the capg components:
+
* Modify the `capg-manager-bootstrap-credentials` secret in `capg-system`, aligning it with `keoscluster-settings` in `kube-system`.
+
* Restart the `capg-controller-manager` deployment in `capg-system`.

. Update the _secrets.yml_ file:
+
* Follow the procedure indicated in the xref:stratio-keos:operations-guide:cluster-operation/credentials.adoc[Stratio KEOS credential management documentation].