= Installation

== Prerequisites

=== EKS

* Roles and policies
+
For automated provisioning on EKS, actions must be executed on various services, such as EC2, ECR, EKS, and Elastic Load Balancing (ELB), among others. Although these actions can vary by installation type, the provider verifies that the indicated user has the required permissions to ensure correct operation.
+
** xref:attachment$stratio-eks-policy.json[Download permanent permissions for EKS]
** xref:attachment$stratio-aws-temp-policy.json[Download temporary permissions for EKS]
+
For EKS deployment, you must manually create the "AWSServiceRoleForAmazonEKS" role and associate the "AmazonEKSServiceRolePolicy" policy (created by default in AWS) with it.
+
[[eks_nodegroup_permissions]]
+
NOTE: If the cluster includes _MachinePool_ type groups (nodegroups managed by EKS), the deployment user needs additional permissions: `eks:CreateNodegroup`, `eks:DescribeNodegroup`, `eks:DeleteNodegroup`, `autoscaling:DescribeAutoScalingGroups`, and `iam:CreateServiceLinkedRole`. These permissions are already included in the _stratio-eks-policy.json_ file.

* Certified operating systems
+
To ensure compatibility between the worker nodes and the _control-plane_ managed by EKS, use correctly configured operating system images. It is recommended to generate these images with https://github.com/kubernetes-sigs/image-builder[Kubernetes Image Builder], the official Kubernetes project tool to create images optimized for cloud providers. You can consult the https://image-builder.sigs.k8s.io/[official documentation] for more details on how to build custom images.

NOTE: Alternatively, the public images provided by AWS in the format `amazon-eks-node-<k8s-version>-v<date>` are also valid and meet the requirements to deploy _Stratio KEOS_ on EKS.

The currently recommended operating system for this provider is Ubuntu 22.04.

* AWS CloudFormation
+
WARNING: If you have not created the AWS CloudFormation stack or have not previously created the IAM requirements in the account, you must set the parameter `spec.security.aws.create_iam` to _true_ (default is _false_).

=== GKE

* Permissions.
+
On GKE, the service account that provisions the clusters must have the following sets of permissions.
+
** xref:attachment$stratio-gcp-permissions.list[Download permissions for GCP].
** xref:attachment$stratio-gke-permissions.list[Download permissions for GKE].

* Certified operating systems.
+
On GKE, the default operating system is Container-Optimized OS (COS), so you don't need to specify a particular image.

* Enable the Google Kubernetes Engine (GKE) API.
* Bastion.
+
To deploy _Stratio KEOS_ on GKE, you need a bastion that facilitates communication with the cluster. Create it in the same network as the cluster.
+
Since Kubernetes 1.35, the bastion VM must have "cgroup v2" enabled. The kubelet preflight check (`system-validators v1.12.1`) throws an error, not a warning, if it detects "cgroup v1" on the host. This occurs with kubelet v1.35 and later. To enable "cgroup v2" on the bastion:
+
[source,bash]
----
sudo sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1 cgroup_no_v1=all"/' /etc/default/grub
sudo update-grub
sudo reboot
----
+
After the reboot, check the change with `stat -fc %T /sys/fs/cgroup/`; it must return "cgroup2fs".
+
Reference: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.35.md[Kubernetes v1.35 CHANGELOG].

=== Unmanaged Azure

* Permissions
+
To provision on unmanaged Azure, you need an account with all the required permissions, as with other supported providers. In addition, you must define:
+
** A role for the cluster's workers in `spec.security.nodes_identity`.
** A role for the _control-plane_ in `spec.security.control_plane_identity`.
+
For the case of subscription-level permissions, it is recommended:
+
** xref:attachment$stratio-azure-role.json[Download permissions for the Azure deployment user].
** xref:attachment$stratio-azure-nodes-role.json[Download permissions for Azure workers].
** xref:attachment$stratio-azure-cp-role.json[Download permissions for the Azure control-plane].
+
For the case of resource group-level permissions, it is recommended:
+
** xref:attachment$stratio-azure-role-rg.json[Download permissions for the Azure deployment user].
** xref:attachment$stratio-azure-nodes-role-rg.json[Download permissions for Azure workers].
** xref:attachment$stratio-azure-cp-role-rg.json[Download permissions for the Azure control-plane].
** xref:attachment$stratio-azure-acr.json[Download permissions for the Azure deployment user, workers, and control-plane].
** In addition, these permissions must be assigned at the resource group level:
*** Deployment user: `Acrpull` on `/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.ContainerRegistry/registries/<acr_name>`
*** Control-plane: `Acrpull` on `/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.ContainerRegistry/registries/<acr_name>`
*** Workers: `Acrpull` on `/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.ContainerRegistry/registries/<acr_name>`

* Certified operating systems
+
To ensure compatibility between the control plane and worker nodes in unmanaged Azure environments, you must use correctly configured images. We recommend generating them with https://github.com/kubernetes-sigs/image-builder[Kubernetes Image Builder], an official Kubernetes project tool that creates images adapted to different cloud providers. See the https://image-builder.sigs.k8s.io/[official Image Builder documentation] to learn how to build custom images.

The recommended operating system is Ubuntu 22.04, which the Azure controller configures by default.

=== Considerations for images

For the _control-plane_, you can't specify an image on EKS or GKE, but you can on unmanaged Azure.

For worker nodes on unmanaged Azure, specifying the image is optional (if not specified, the controller assigns an available image provided by the cloud provider).

When creating the image for the cluster, you must account for the operating system needs of the applications that require them (systemd units, DaemonSets, and so on) and the Kubernetes version to use.

==== Elasticsearch

To support Elasticsearch deployments, the operating system must have the `vm.max_map_count = 262144` sysctl parameter, as indicated in its https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html[official documentation].

The Amazon Linux 2 images *used by EKS* already include this parameter and its value.

== Cluster descriptor

To indicate the cluster's particularities, use the _KeosCluster_ resource in a manifest file. The header of this descriptor will be the same as that of any Kubernetes resource:

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
spec:
----

=== _metadata_

The _metadata_ of the _KeosCluster_ resource is composed of the following fields:

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

|_name_
|Name of the cluster.
|my-cluster
|No
|===

=== _spec_

The _spec_ field of the _KeosCluster_ resource includes the following parameters:

[cols="1,1,4,2,1,1"]
|===
^|Name ^|Type ^|Description ^|Example ^|Optional ^|Default value

|_control++_++plane_
|Object
|Kubernetes _control-plane_ configuration.
|See <<ejemplo_de_descriptor, descriptor example>>
|No
|-

|_credentials_
|Object
|Cloud provider credentials used during provisioning.
|See the <<_descriptor_example, descriptor example>>
|No on the first execution.
|-

|_deploy++_++autoscaler_
|Boolean
|Indicates whether the _cluster-autoscaler_ should be deployed on the cluster.
|See <<_descriptor_example, descriptor example>>
|Yes.
|_true_.

|_dns_
|Object
|External DNS configuration for _Stratio KEOS_.
|See <<_descriptor_example, descriptor example>>
|Yes.
|_manage++_++zone_ is _true_ by default.

|_docker++_++registries_
|Array
|List of Docker registries accessible from the nodes.
|See <<_descriptor_example, descriptor example>>
|No
|-

|_external++_++domain_
|String
|External domain accessible outside the cluster.
|See <<_descriptor_example, descriptor example>>
|No
|-

|_helm++_++repository_
|Object
|Helm repository to install the Stratio charts.
|See <<_descriptor_example, descriptor example>>
|No
|-

|_infra++_++provider_
|String
|Name of the cloud provider (AWS, GCP, or Azure).
|aws
|No
|-

|_k8s++_++version_
|String
|Kubernetes version of the cluster. It must be compatible with the cloud provider and with _Stratio KEOS_. On EKS, the patch version is not considered.
|v1.26.8
|No
|-

|_keos_
|Object
|Parameters for the installation of _Stratio KEOS_.
|See <<_descriptor_example, descriptor example>>
|No
|-

|_networks_
|Object
|Identifiers of the previously created infrastructure.
|See <<_descriptor_example, descriptor example>>
|Yes
|-

|_region_
|String
|Cloud provider region used in the provisioning.
|eu-west-1
|No
|-

|_security_
|Object
|Configuration of identities and access controls, adapted to each provider.
|See <<_descriptor_example, descriptor example>>
|Azure (No) AWS (Yes) GCP (Yes)
|-

|_storageclass_
|Object
|Configuration of the default _StorageClass_ of the cluster.
|See <<_descriptor_example, descriptor example>>
|Yes
|-

|_worker++_++nodes_
|Array
|Configuration of the worker node groups.
|See <<_descriptor_example, descriptor example>>
|No
|-
|===

=== Credentials

On the first execution, this section indicates the credentials for provisioning on the cloud provider.

These secrets are encrypted with a passphrase requested during the provisioning in the _secrets.yml_ file, thus eliminating the entire credentials section from the descriptor. In subsequent executions, the passphrase is simply requested to decrypt the secrets file, from which the credentials are read.

The following fields are considered provisioning secrets:

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

|_aws_
|Credentials for access to AWS.
|See the <<_descriptor_example, descriptor example>>
|No

|_azure_
|Credentials for access to Azure.
|See the <<_descriptor_example, descriptor example>>
|No

|_gke_
|Credentials for access to GKE.
|See the <<_descriptor_example, descriptor example>>
|No

|_github++_++token_
|GitHub token. You can use a fine-grained token or a classic token; neither requires any permissions. To generate it, go to: 'Settings' → 'Developer settings' → 'Personal access tokens'.
|_github++_++pat++_++11APW_
|Yes

|_docker++_++registries_
|Docker registries accessible from the nodes. For EKS, authentication is not required, since it is performed automatically with the user's credentials.
|See the <<_descriptor_example, descriptor example>>
|Yes, for non-authenticated registries.

|_helm++_++repository_
|Helm repository for the installation of the Stratio charts.
|See the <<_descriptor_example, descriptor example>>
|Yes, for non-authenticated repositories.
|===

=== Credentials for registries and repositories

Provide credentials to access Docker registries and Helm repositories when authentication is required.

==== Credentials for Docker registries

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

|_url_
|URL of the Docker registry that requires authentication.
|registry.example.com/org/repo
|No

|_user_
|Username to authenticate in the Docker registry.
|user
|No

|_pass_
|Password to authenticate in the Docker registry.
|password
|No
|===

==== Credentials for Helm repositories

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

|_url_
|URL of the Helm repository that requires authentication.
|https://charts.example.com
|No

|_user_
|Username to authenticate in the Helm repository.
|user
|No

|_pass_
|Password to authenticate in the Helm repository.
|password
|No
|===

NOTE: Any change in _spec.credentials_ must include all the necessary credentials in the cluster descriptor and previously delete the _secrets.yml_ file.

=== Security

The `security` block centralizes identity and access-control configuration for cluster resources and adapts to different cloud providers. It lets you define identities for both the _control-plane_ and the nodes, and includes specific options for AWS and GCP.

[cols="1,4,2,1,1"]
|===
^|Name ^|Description ^|Example ^|Optional ^|Provider

|_control++_++plane++_++identity_
|Identity (role, service account, and so on) used by the cluster _control-plane_.
|/subscriptions/6e2a38cd-../stratio-control-plane
|No
|Azure

|_nodes++_++identity_
|Identity (role, service account, and so on) used by the worker nodes. +
On GKE, it is the nodes' default service account.
|/subscriptions/6e2a38cd-../stratio-nodes/gke-node-sa@my-project-id.iam.gserviceaccount.com
|No/Yes
|Azure/GCP

|_aws.create++_++iam_
|Indicates whether specific IAM resources must be created for the cluster during provisioning.
|false
|Yes (default value: _false_)
|AWS

|_gcp.scopes_
|List of scopes available for the service account of the nodes, which control the access permissions to GCP services.
a|

[source,yaml]
----
scopes:
  - https://www.googleapis.com/auth/userinfo.email
  - https://www.googleapis.com/auth/cloud-platform
----

|Yes
|GCP
|===

=== Docker repositories

Indicate the Docker repositories used during installation. This section lets you configure the repository URL, its type, and whether it requires authentication.

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

| _auth++_++required_
| Indicates whether the repository requires authentication.
| _false_
| No.

| _type_
| Type of Docker repository.
| acr, ecr, gar, gcr, generic
| No

| _url_
| URL of the repository.
| AABBCC.dkr.ecr.eu-west-1.amazonaws.com/keos
| No

| _keos++_++registry_
| Indicates whether this repository is used for the _Stratio KEOS_ images.
| _true_
| No. At least one repository must be marked as _keos++_++registry_.
|===

NOTE: The `ecr_pull_through_cache_enabled` parameter is a day-0 configuration; you must configure it when creating the cluster. Activating it in an existing cluster does not affect already deployed workloads.

==== Prerequisites for `ecr_pull_through_cache_enabled`

Before creating a cluster with `ecr_pull_through_cache_enabled: true`, verify that the AWS account meets the following requirements:

* Pull-through cache rules configured in Amazon ECR for the five upstreams used by _Stratio KEOS_: `registry.k8s.io`, `docker.io`, `ghcr.io`, `quay.io`, and `public.ecr.aws`.
* IAM permissions on the node role: `ecr:BatchImportUpstreamImage` and `ecr:CreateRepository`.

If you have `spec.security.aws.create_iam: true` in the descriptor, _Stratio Cloud Provisioner_ adds these permissions automatically when creating the cluster. If you manage the IAM resources manually (`create_iam: false`) or need to enable them in an existing account, update the AWS CloudFormation stack with `clusterawsadm`:

NOTE: The AWS user with which you run `clusterawsadm` must have the permissions defined in the xref:attachment$stratio-aws-temp-policy.json[stratio-aws-temp-policy.json] file.

[source,bash]
----
cat > /tmp/eks.config << 'EOF'
apiVersion: bootstrap.aws.infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSIAMConfiguration
spec:
  bootstrapUser:
    enable: false
  eks:
    enable: true
    iamRoleCreation: false
    defaultControlPlaneRole:
        disable: false
  controlPlane:
    enableCSIPolicy: true
  nodes:
    extraPolicyAttachments:
    - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    extraStatements:
    - Action:
        - "ecr:BatchImportUpstreamImage"
        - "ecr:CreateRepository"
      Effect: Allow
      Resource:
        - "*"
EOF

clusterawsadm bootstrap iam create-cloudformation-stack \
  --config /tmp/eks.config \
  --region <region>
----

=== Use of `role_arn` in the credentials descriptor

You can also define the `role_arn` directly in the credentials descriptor to automatically use assume-role:

[source,yaml]
----
credentials:
    aws:
        role_arn: arn:aws:iam::<accountID>:role/my-aws-role
----

NOTE: This parameter is optional. Assume role will only be used if `role_arn` is defined in the descriptor.

NOTE: The prerequisites are the same as those indicated in the xref:operations-manual:operations-manual.adoc#_prerequisites[Enable authorization through assume role in AWS for an EKS cluster] section of the operations manual.

=== Helm repository

As an installation prerequisite, the Helm repository from which the _Cluster Operator_ chart can be extracted must be indicated. This section lets you specify the repository URL, its type, and whether it is authenticated.

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

| _auth++_++required_
| Indicates whether the repository is authenticated.
| _false_
| Yes. Default: _false_.

| _url_
| URL of the repository.
| *OCI repositories*: oci://stratioregistry.azurecr.io/helm-repository-example +
*HTTPS repositories*: https://[IP]:8080
| No

| _type_
| Type of the repository.
| _generic_ or ecr.
| Yes. Default: _generic_.
|===

NOTE: OCI repositories (from cloud providers such as ECR, GAR, or ACR) never require authentication. Authentication will be performed through the credentials used during the provisioning. Please verify in the _Stratio KEOS_ documentation which repositories are supported for the version you use.

=== Networks

As mentioned, the installer lets you use previously created cloud provider network elements (for example, by a network security team), allowing you to implement the architecture that best fits your needs.

Both the VPC and the subnets must be created in the cloud provider. The subnets can be private or public, but in the latter case they must have a NAT gateway and an Internet Gateway in the same VPC. In case of indicating subnets of both types, the worker nodes will be deployed in private subnets.

_Stratio KEOS_ will not manage the lifecycle of previously created objects.

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

|_vpc++_++id_
|VPC ID.
|vpc-0264503b8761ff69f
|Yes

|_subnets_
|Array of subnet IDs.
a|

[source,yaml]
----
- subnet_id: subnet-0df..
- subnet_id: subnet-887..
----

|Yes
|===

=== _control-plane_

This section details the particularities of the Kubernetes _control-plane_.

[cols="^1,4,3,^1"]
|===
^|Name ^|Description ^|Example ^|Optional

|_aws_
|Values specific to EKS. Includes the configuration of the _control-plane_ logging ("api", "audit", "authenticator", "controllerManager", or "scheduler"). It also includes the name of a preexisting IAM role for managed node groups (_MachinePool_) (_mp++_++role++_++name_). It is optional: if not specified and the AWS account is already prepared for EKS (see below), a default role is used automatically.
a|

[source,yaml]
----
logging:
  api_server: true
----

[[mp_role_name_ownership]]

IMPORTANT: If `mp_role_name` is not specified, CAPA automatically searches for the default role `eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io`. This role is created by the `clusterawsadm bootstrap iam create-cloudformation-stack` command, executed on the AWS account in two possible ways:

* *Automatically by _Stratio Cloud Provisioner_* when `security.aws.create_iam: true` — invokes that same command as part of the installation.
* *Manually by the user*, as prior preparation of the AWS account for EKS/CAPA (usual prerequisite in accounts already used with previous versions), with `security.aws.create_iam: false`.

In both cases, the result is the same CloudFormation stack with the same role name, so you don't need to run it again or specify `mp_role_name` if the account has already gone through that bootstrap at some point.

`mp_role_name` is only necessary if you want to use your own IAM role, with a name different from that of the default role — in that case, it is the user's responsibility to create it before the installation with, at a minimum, these policies (the ones that EKS requires from any worker node, regardless of _Stratio Cloud Provisioner_): `AmazonEKSWorkerNodePolicy`, `AmazonEKS_CNI_Policy`, `AmazonEC2ContainerRegistryReadOnly`. Indicating a nonexistent role here causes the creation of any `MachinePool` to fail on the first attempt.

[[nodegroup_extra_policy_arn]]

IMPORTANT: If the cluster is going to have `docker_registries[].ecr_pull_through_cache_enabled: true`, the `MachinePool` nodes also need the permissions `ecr:BatchImportUpstreamImage`/`ecr:CreateRepository`. The `eks-nodegroup` role (unlike `nodes`) *does not support inline policies* — only policies managed by ARN. With `security.aws.create_iam: true`, first create an independent IAM policy with those permissions and indicate it in `security.aws.nodegroup_extra_policy_arn`; _Stratio Cloud Provisioner_ automatically attaches it to the `eks-nodegroup` role (alongside `AmazonEBSCSIDriverPolicy`) during the installation. This field *only applies to new installations*; in an existing cluster with the IAM stack created before this functionality, the policy must be attached manually (see xref:operations-manual:upgrade.adoc#_migration_to_ecr_pull_through_cache[Migration to ECR pull-through cache]).

|Yes

|_gcp_
|Values specific to the GKE _control-plane_ (_private++_++cluster_, _master++_++authorized++_++networks++_++config_, _ip++_++allocation++_++policy_, _monitoring++_++config_, and _logging++_++config_).
a|

[source,yaml]
----
cluster_network:
  private_cluster:

master_authorized_networks_config:

ip_allocation_policy:

monitoring_config:

logging_config:

cluster_security:
  workload_identity_config:
----

|See the quick start guide for more information.

|_managed_
|Indicates whether the _control-plane_ is managed or not by the cloud provider.
|true
|No
|===

=== Worker nodes

This section specifies the worker node groups and their characteristics.

The images used must be supported by EKS. See the https://docs.aws.amazon.com/es_es/eks/latest/userguide/eks-optimized-ami.html[creation of custom AMI for EKS].

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

|_name_
|Name of the group. It will be used as a prefix for the instances.
|eks-prod-gpu
|No

|_quantity_
|Number of nodes in the group. It is recommended to be a multiple of 3 to avoid imbalances.
|15
|No

|_size_
|Type of instance.
|t3.medium
|No

|_max++_++size_/_min++_++size_
|Maximum and minimum number of instances for autoscaling.
|6/18.
|Yes

|_az_
|Zone for the entire group (overrides the _zone++_++distribution_ parameter).
|eu-east-1a
|Yes

|_zone++_++distribution_
|Indicates whether the nodes will be distributed equally across the zones (by default) or not.
|unbalanced
|Yes

|_node++_++image_
|Custom instance image for the worker nodes. If specified in a managed EKS cluster, the node group is created as a _MachineDeployment_ (self-managed EC2 node). It is mutually exclusive with _ami++_++type_.
|ami-0de933c15c9b49fb5
|Yes

|_ami++_++type_
|AMI type for the node group managed by EKS (_MachinePool_). Only valid with a managed _control-plane_. If not specified, "BOTTLEROCKET++_++x86++_++64" is used by default. It is mutually exclusive with _node++_++image_.
|BOTTLEROCKET++_++x86++_++64
|Yes

|_spot_
|Activates the use of spot instances in the node group. Allows reducing costs in exchange for a higher risk of interruptions.
|true
|Yes

|_labels_
|Kubernetes labels for the worker nodes.
a|

[source,yaml]
----
labels:
  disktype: standard
  gpus: true
----

|Yes

|_additional++_++labels_
|Optional set of additional labels that will be applied to the node groups (node pools), in addition to the labels configured by default. +
This field is only available in GKE deployments.
a|

[source,yaml]
----
additional_labels:
  goog-gke-node-pool-provisioning-model: on-demand
  environment: production
  team: data
----

|Yes

|_root++_++volume_
|Particularities of the volume, such as size, type, and encryption.
a|

[source,yaml]
----
root_volume:
  size: 50
  type: gp3
  encrypted: true
----

|Yes

|_ssh++_++key_
|Public SSH key to access the worker nodes. It must be created in AWS beforehand. It is recommended not to add any SSH key to the nodes.
|prod-key
|Yes
|===

NOTE: The option to set a _min++_++size_ to zero has been implemented, which allows autoscaling to increase or decrease the number of nodes down to zero as needed. This functionality provides significant cost savings compared to previous versions, since it lets you define a worker group without instantiating any unnecessary resources in the cloud provider.

NOTE: On EKS clusters with a managed control-plane, the type of node group depends on the _node++_++image_ field. If it is present, a _MachineDeployment_ (self-managed EC2) is created. If it is not present, a _MachinePool_ (a group managed by EKS) is created. A cluster can combine both types. To scale a _MachinePool_ to zero replicas, _max++_++size_ must be greater than or equal to the number of availability zones of the cluster.

=== _Stratio KEOS_

This section lists the parameters for the _keos-installer_ phase.

[cols="1,4,2,1"]
|===
^|Name ^|Description ^|Example ^|Optional

|_flavour_
|Installation flavor that indicates the size of the cluster and its resilience. By default, it is "production".
|development
|Yes

|_version_
|Version of the _keos-installer_.
|1.0.0
|No
|===

=== Descriptor example

Two use cases of the descriptor demonstrate the capability of _Stratio Cloud Provisioner_ in both supported cloud providers.

==== EKS

In this example, the following particularities can be seen:

* Cluster on AWS with managed _control-plane_ (EKS).
* Kubernetes version 1.26.x (EKS does not consider the patch version).
* Use of ECR as a Docker registry (does not require credentials).
* Use of custom VPC and subnets (previously created). This section is optional.
* Definition of a default _StorageClass_. This section is optional.
* The _API Server_ logs are enabled on EKS.
* Use of node groups managed by EKS (_MachinePool_): the groups without _node++_++image_ are created as _MachinePools_ with an AMI managed by EKS.
* Fixed IAM role for the managed node groups (_mp++_++role++_++name_): with `create++_++iam: true`, _Stratio Cloud Provisioner_ already creates the role `eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io` as part of its own CloudFormation stack; the full name is indicated here so that `MachinePool` uses it instead of creating a dynamic role per nodegroup.
* Coexistence of managed groups (_MachinePool_) and groups with custom AMI (_MachineDeployment_): the group with _node++_++image_ is created as a _MachineDeployment_ (self-managed EC2).
* Worker node groups with several cases:
** Different instance types.
** With explicit _ami++_++type_ ("BOTTLEROCKET++_++x86++_++64") and with default AMI.
** With SSH key.
** With Kubernetes labels.
** With autoscaling ranges.
** In a fixed zone.
** With customizations on the disk (only apply to the _MachineDeployment_ group with custom AMI; see the note after the example).
** With spot type instances.
** AZ distribution cases: balanced and unbalanced.

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
  name: eks-prod
spec:
  infra_provider: aws
  credentials:
    aws:
      region: eu-west-1
      access_key: AKIAT4..
      account_id: '3683675..'
      secret_key: wq3/Vsc..
      role_arn: arn:aws:iam::3683675..:role/my-aws-role
    github_token: github_pat_11APW..
  k8s_version: v1.32.x
  region: eu-west-1
  external_domain: domain.ext
  networks:
    vpc_id: vpc-02698..
    subnets:
      - subnet_id: subnet-0416d..
      - subnet_id: subnet-0b2f8..
      - subnet_id: subnet-0df75..
  docker_registries:
    - url: AABBCC.dkr.ecr.eu-west-1.amazonaws.com/keos
      auth_required: false
      type: ecr
      keos_registry: true
  helm_repository:
    auth_required: false
    url: http://charts.stratio.com
  storageclass:
    parameters:
      type: gp3
      fsType: ext4
      encrypted: "true"
      labels: "owner=stratio"
  dns:
    manage_zone: false
  deploy_autoscaler: false
  keos:
    flavour: production
    version: 1.3.x
  security:
    aws:
      create_iam: true
  control_plane:
    aws:
      logging:
        api_server: true
      mp_role_name: "eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io"
    managed: true
  worker_nodes:
    - name: eks-prod-xlarge
      quantity: 6
      max_size: 18
      min_size: 6
      size: m6i.xlarge
      ami_type: BOTTLEROCKET_x86_64
      labels:
        disktype: standard
      root_volume:
        size: 50
        type: gp3
        encrypted: true
      ssh_key: stg-key
    - name: eks-prod-medium-spot
      quantity: 4
      min_size: 4
      max_size: 8
      zone_distribution: unbalanced
      size: t3.medium
      spot: true
      labels:
        disktype: standard
    - name: eks-prod-medium-az
      quantity: 3
      min_size: 3
      max_size: 6
      size: t3.medium
      az: eu-west-1c
    - name: eks-prod-custom-ami
      quantity: 2
      max_size: 6
      min_size: 2
      size: m6i.large
      node_image: "ami-0a1234567890abcde"
      labels:
        workload: custom
----

NOTE: The `eks-prod-xlarge` group is a _MachinePool_ group (without `node_image`). In _MachinePool_, `root_volume.type` and `root_volume.encrypted` have no effect: EKS manages the nodegroup root volume and doesn't expose those options unless you use an AWS Launch Template, which isn't currently supported. These fields only apply to _MachineDeployment_ groups with a custom AMI, such as `eks-prod-custom-ami` in this same example.

==== Known limitations — _MachinePool_ (EKS)

[%header,cols="2,3"]
|===
| Limitation
| Note

| Custom AMI (`ami_id`) not supported in _MachinePool_
| Use `ami_type` or switch to _MachineDeployment_ (`node_image`) if you need a specific AMI.

| Separate CRI volume (`cri_volume`) not supported in _MachinePool_
|

| `ami++_++type` in _MachinePool_ only supports `BOTTLEROCKET_x86_64`/`BOTTLEROCKET_x86_64_NVIDIA`
|

| Single instance type per _MachinePool_ (no fallback to another type within the same group)
|

| `quantity: 0` requires `max_size >= 1`; in balanced mode (several AZs), `max_size` must be ≥ number of AZs
|

| _MachinePool_ EC2 instances without a visible `Name` tag in the AWS console
| They are identifiable by the tags `kubernetes.io/cluster/<name>` and `eks:nodegroup-name`.
|===

==== GKE

In this example, the following particularities can be seen:

* Cluster on GCP with managed control-plane.
* Kubernetes version 1.28.x.
* Use of a _gar_ type Docker registry.
* Use of a _gar_ type Helm repository.
* _enable++_++secure++_++boot_ (enabled by default).
* _nodes++_++identity_ (default service account for the nodes). (Only configurable at the time of cluster creation).
* _scopes_ (list of scopes available for this service account).
* Without control of the DNS zone (enabled by default).
* Definition of a default _StorageClass_. This section is optional.
* Characteristics of the control-plane: only configurable at the time of cluster creation.
** _cluster++_++network_
*** _private++_++cluster_
**** _enable++_++private++_++endpoint_
**** _enable++_++private++_++nodes_
**** _control++_++plane++_++cidr++_++block_
** _ip++_++allocation++_++policy_
*** _cluster++_++ipv4++_++cidr++_++block_
*** _services++_++ipv4++_++cidr++_++block_
*** _cluster++_++secondary++_++range++_++name_
*** _services++_++secondary++_++range++_++name_
** _monitoring++_++config_
*** _enable++_++managed++_++prometheus_
** _master++_++authorized++_++networks++_++config_
*** _cidr++_++blocks_
*** _gcp++_++public++_++cidrs++_++access++_++enabled_
** _logging++_++config_
*** _system++_++components_
*** _workloads_
* Worker node groups with several cases:
** Different instance types.
** Without a specific image (the default image of the cloud provider will be used).
** With K8s labels.
** With autoscaling ranges.
** In a fixed zone.
** With customizations on the disk.

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
  name: gcp-prod
spec:
  infra_provider: gcp
  credentials:
    gcp:
      private_key_id: "efdf19f5605a.."
      private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvw.."
      client_email: keos@stratio.com
      project_id: gcp-prod
      region: europe-west4
      client_id: "6767910929.."
  security:
    nodes_identity: "gke-node-sa@my-project-id.iam.gserviceaccount.com"
    gcp:
      scopes:
        - "https://www.googleapis.com/auth/cloud-platform"
        - "https://www.googleapis.com/auth/userinfo.email"
    enable_secure_boot: true
  k8s_version: v1.32.x
  region: europe-west4
  docker_registries:
      - url: europe-docker.pkg.dev/stratio-keos/keos
        auth_required: false
        type: gar
        keos_registry: true
  helm_repository:
      auth_required: false
      url: http://charts.stratio.com
      type: gar
  dns:
    manage_zone: false
  external_domain: domain.ext
  networks:
    vpc_id: gcp-prod-vpc
    subnets:
      - subnet_id: gcp-prod-subnet
  storageclass:
    parameters:
      type: pd-standard
      fsType: ext4
      replication-type: none
      labels: "owner=stratio"
  keos:
    flavour: production
    version: 1.3.x
  control_plane:
    managed: true
    gcp:
      cluster_network:
        private_cluster:
          enable_private_endpoint: true
          enable_private_nodes: true
          control_plane_cidr_block: 172.16.16.0/28
      ip_allocation_policy:
        cluster_ipv4_cidr_block: 172.16.0.0/16
        services_ipv4_cidr_block: 172.17.0.0/20
        cluster_secondary_range_name: "gkepods-europ-west1"
        services_secondary_range_name: "gkeservices-europe-west1"
      monitoring_config:
        enable_managed_prometheus: false
      master_authorized_networks_config:
        cidr_blocks:
          - cidr_block: 192.168.100.0/24
            display_name: Office Network
          - cidr_block: 172.16.0.0/20
            display_name: VPC Network
        gcp_public_cidrs_access_enabled: false
      logging_config:
        system_components: false
        workloads: false
      cluster_security:
        workload_identity_config:
          enabled: true
          workload_pool: gcp-prod.svc.id.goog
          service_accounts:
            flux: flux-gke-sa@gcp-prod.iam.gserviceaccount.com
  worker_nodes:
    - name: gcp-prod-xlarge
      quantity: 6
      max_size: 18
      min_size: 6
      size: c2d-highcpu-8
      labels:
        disktype: standard
      root_volume:
        size: 50
        type: pd-standard
        encrypted: true
        encryption_key: projects/gcp-prod/locations/europe-west4/keyRings/keos-keyring/cryptoKeys/keos-key
    - name: gcp-prod-medium-az
      quantity: 3
      size: c2d-highcpu-4
      az: europe-west4-a
---
apiVersion: installer.stratio.com/v1beta1
kind: ClusterConfig
metadata:
    name: gcp-prod-config
spec:
    private_registry: true
    private_helm_repo: true
    cluster_operator_version: 0.8.x
    cluster_operator_image_version: 0.8.x
----

==== Unmanaged Azure

In this example, the following particularities can be seen:

* Cluster on Azure with unmanaged control-plane.
* Use of ACR as a Docker registry (does not require credentials).
* Use of a specific CIDR for pods.
* Definition of a default _StorageClass_. This section is optional.
* Characteristics of the virtual machines for the _control-plane_:
** With high availability (3 instances are deployed).
** With a specific instance type.
** Without a specific image (optional for this cloud provider).
** With customizations on the disk.
* Worker node group:
** With a specific image (optional for this cloud provider).
+
NOTE: Image component versions must align with the indicated Kubernetes version.

** With K8s labels.
** With autoscaling ranges.
** With customizations on the disk.

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
  name: azure-prod
spec:
  infra_provider: azure
  credentials:
    azure:
      client_id: ee435ab0..
      client_secret: lSF8Q~n..
      subscription_id: '6e2a38cd-e..'
      tenant_id: '9c2f8eb6-5..'
  k8s_version: v1.32.x
  region: westeurope
  docker_registries:
    - url: eosregistry.azurecr.io/keos
      auth_required: false
      type: acr
      keos_registry: true
  helm_repository:
    auth_required: false
    url: http://charts.stratio.com
  storageclass:
    parameters:
      type: StandardSSD_LRS
      fsType: ext4
      tags: "owner=stratio"
  external_domain: domain.ext
  dns:
    manage_zone: false
  keos:
    flavour: production
    version: 1.3.x
  security:
    control_plane_identity: "/subscriptions/6e2a38cd-../stratio-control-plane"
    nodes_identity: "/subscriptions/6e2a38cd-../stratio-nodes"
  control_plane:
    managed: false
    size: Standard_D8_v3
    node_image: "/subscriptions/6e2a38cd-../images/capi-ubuntu-2204-1687262553"
    root_volume:
      size: 100
      type: StandardSSD_LRS
  worker_nodes:
    - name: azure-prod-std
      quantity: 3
      max_size: 18
      min_size: 3
      size: Standard_D8_v3
      node_image: "/subscriptions/6e2a38cd-../images/capi-ubuntu-2204-1687262553"
      labels:
        backup: "false"
      root_volume:
        size: 100
        type: StandardSSD_LRS
----

== Creation of the cluster

_Stratio Cloud Provisioner_ automates provisioning of the necessary resources in the specified cloud provider to create a Kubernetes cluster from the <<_cluster_descriptor, descriptor>> indicated.

The binary currently offers the following options:

- `--avoid-creation`: does not create the worker cluster, only the local cluster.
- `--build-stratio-image`: instead of downloading the _Stratio Cloud Provisioner_ image, it builds it locally and uses it. This option is intended only for development.
- `--delete-previous`: deletes the local cluster container if it already exists.
- `-d, --descriptor <string>`: allows specifying the name of the descriptor located in the current directory or another. Default: _cluster.yaml_.
- `-h, --help`: shows the help of the command.
- `--keep-mgmt`: keeps the management of the cluster on kind (only in *non-production* environments).
- `--local-stratio-image-version <string>`: overrides the local version of the _Stratio Cloud Provisioner_ image when `use-local-stratio-image` is used.
- `-n, --name <string>`: name of the cluster; overrides the `KIND_CLUSTER_NAME` variable. Default value: _kind_.
- `--retain`: retains the nodes for debugging in case the cluster creation fails.
- `--use-local-stratio-image`: uses the local _Stratio Cloud Provisioner_ image without building it or downloading it.
- `--validate-only`: validates the descriptor without creating the cluster.
- `-p, --vault-password <string>`: sets the Vault password to encrypt the secrets.

To create a cluster, a simple command is enough (see the particularities of each provider in their quick start guides):

[source,bash]
-----
sudo ./cloud-provisioner create cluster --name stratio-pre --descriptor cluster-gcp.yaml
Vault Password:
Creating temporary cluster "stratio-pre" ...
 ✓ Ensuring node image (kindest/node:v1.27.0) 🖼
 ✓ Building Stratio image (cloud-provisioner:<version>) 📸
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✓ Installing CAPx 🎖️
 ✓ Generating secrets file 📝🗝️
 ✓ Installing keos cluster operator 💻
 ✓ Creating the workload cluster 💥
 ✓ Saving the workload cluster kubeconfig 📝
 ✓ Installing Calico in workload cluster 🔌
 ✓ Installing CSI in workload cluster 💾
 ✓ Creating Kubernetes RBAC for internal loadbalancing 🔐
 ✓ Preparing nodes in workload cluster 📦
 ✓ Installing StorageClass in workload cluster 💾
 ✓ Enabling workload clusters self-healing 🏥
 ✓ Installing CAPx in workload cluster 🎖️
 ✓ Configuring Network Policy Engine in workload cluster 🚧
 ✓ Installing cluster-autoscaler in workload cluster 🗚
 ✓ Installing keos cluster operator in workload cluster 💻
 ✓ Creating cloud-provisioner Objects backup 🗄️
 ✓ Moving the management role 🗝️
 ✓ Executing post-install steps 🎖️
 ✓ Generating the KEOS descriptor 📝

The cluster has been installed successfully. Please refer to the documents below on how to proceed:
1. Post-installation _Stratio Cloud Provisioner_ documentation.
2. _Stratio KEOS_ documentation.
-----

Once the process is finished, you will have the necessary files (_keos.yaml_ and _secrets.yml_) to install _Stratio KEOS_.

NOTE: Since the installation descriptor file (_keos.yaml_) is regenerated on each execution, a backup of the previous one is made in the local directory with the corresponding date (e.g., _keos.yaml.2023-07-05@11:19:17~_).

[[_actualización_de_cluster_autoscaler]]

=== Upgrade of _cluster-autoscaler_ after installation

Applies to EKS with _MachinePool_ groups and `deploy_autoscaler: true` (on GKE, _Stratio Cloud Provisioner_ does not deploy _cluster-autoscaler_).

IMPORTANT: Once the cluster is created, the default _cluster-autoscaler_ image must be replaced with the Stratio image `v1.35.2`. This image includes the fix for the scale-down of _MachinePool_ nodes (https://github.com/kubernetes/autoscaler/pull/9693[kubernetes/autoscaler#9693]), which is not yet included in any official version of _cluster-autoscaler_.

The image is published in `stratio-releases.repo.stratio.com/autoscaling/cluster-autoscaler:v1.35.2`. Replicate it in the cluster's Docker registry (the one marked with `keos_registry: true` in the descriptor) before applying the change:

[source,bash]
----
docker pull stratio-releases.repo.stratio.com/autoscaling/cluster-autoscaler:v1.35.2
docker tag stratio-releases.repo.stratio.com/autoscaling/cluster-autoscaler:v1.35.2 <registry>/autoscaling/cluster-autoscaler:v1.35.2
docker push <registry>/autoscaling/cluster-autoscaler:v1.35.2
----

NOTE: If the registry uses ECR pull-through cache (`ecr_pull_through_cache_enabled`), the image is not served through the cache: the `repository` must point to `<registry>/autoscaling/cluster-autoscaler`, not to `<registry>/k8s/autoscaling/cluster-autoscaler`.

. Add the image to the chart override values:
+
[source,bash]
----
kubectl -n kube-system edit configmap 02-cluster-autoscaler-helm-chart-override-values
----
+
The _ConfigMap_ stores the chart values as text in the `values.yaml` key of the `data` block, and only what is in that key is applied. After installation, `values.yaml` is empty; if it already contains other values, add the `image` block alongside them without deleting them. The `data` block must be left as follows:
+
[source,yaml]
----
data:
  values.yaml: |
    image:
      repository: <registry>/autoscaling/cluster-autoscaler
      tag: v1.35.2
----

. Force the reconciliation of the _HelmRelease_:
+
[source,bash]
----
kubectl -n kube-system annotate helmrelease cluster-autoscaler \
  reconcile.fluxcd.io/requestedAt="$(date -u +%Y-%m-%dT%H:%M:%SZ)" --overwrite
----

. Verify that the pods use the new image:
+
[source,bash]
----
kubectl -n kube-system get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.containers[0].image}{"\n"}{end}' | grep cluster-autoscaler
----

[[_actualización_de_cluster_autoscaler]]
=== Actualización de _cluster-autoscaler_ tras la instalación

Aplica a EKS con grupos _MachinePool_ y `deploy_autoscaler: true` (en GKE, _Stratio Cloud Provisioner_ no despliega _cluster-autoscaler_).

IMPORTANT: Una vez creado el _cluster_, es necesario sustituir la imagen de _cluster-autoscaler_ desplegada por defecto por la imagen propia de Stratio `v1.35.2`. Esta imagen incluye la corrección del escalado a la baja de nodos de _MachinePool_ (https://github.com/kubernetes/autoscaler/pull/9693[kubernetes/autoscaler#9693]), que todavía no está incluida en ninguna versión oficial de _cluster-autoscaler_.

La imagen está publicada en `stratio-releases.repo.stratio.com/autoscaling/cluster-autoscaler:v1.35.2`. Replícala en el registro Docker del _cluster_ (el marcado con `keos_registry: true` en el descriptor) antes de aplicar el cambio:

[source,bash]
----
docker pull stratio-releases.repo.stratio.com/autoscaling/cluster-autoscaler:v1.35.2
docker tag stratio-releases.repo.stratio.com/autoscaling/cluster-autoscaler:v1.35.2 <registro>/autoscaling/cluster-autoscaler:v1.35.2
docker push <registro>/autoscaling/cluster-autoscaler:v1.35.2
----

NOTE: Si el registro utiliza ECR _pull-through cache_ (`ecr_pull_through_cache_enabled`), la imagen no se sirve a través de la caché: el `repository` debe apuntar a `<registro>/autoscaling/cluster-autoscaler`, no a `<registro>/k8s/autoscaling/cluster-autoscaler`.

. Añade la imagen a los valores de _override_ del _chart_:
+
[source,bash]
----
kubectl -n kube-system edit configmap 02-cluster-autoscaler-helm-chart-override-values
----
+
El _ConfigMap_ guarda los valores del _chart_ como texto dentro de la clave `values.yaml` del bloque `data`, y solo se aplica lo que esté dentro de esa clave. Tras la instalación, `values.yaml` está vacío; si ya contiene otros valores, añade el bloque `image` junto a ellos sin borrarlos. El bloque `data` debe quedar así:
+
[source,yaml]
----
data:
  values.yaml: |
    image:
      repository: <registro>/autoscaling/cluster-autoscaler
      tag: v1.35.2
----

. Fuerza la reconciliación del _HelmRelease_:
+
[source,bash]
----
kubectl -n kube-system annotate helmrelease cluster-autoscaler \
  reconcile.fluxcd.io/requestedAt="$(date -u +%Y-%m-%dT%H:%M:%SZ)" --overwrite
----

. Verifica que los _pods_ usan la nueva imagen:
+
[source,bash]
----
kubectl -n kube-system get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.spec.containers[0].image}{"\n"}{end}' | grep cluster-autoscaler
----

=== Load balancer

Due to an error in the controllers (fixed in the master branch but not yet released), the load balancer created in GCP and Azure for the _API Server_ of clusters with unmanaged control planes is configured with a TCP-based health check.

Eventually, this could cause problems if any _control-plane_ node fails, since the load balancer will send requests to _control-plane_ nodes whose port responds but cannot serve them.

To avoid this problem, modify the health check of the created load balancer to use HTTPS and the _/readyz_ path. Keep the port at 443 for GCP and 6443 for Azure.

=== Automatic labels on GKE

GKE automatically applies several labels to the cluster resources, such as Compute Engine virtual machine instances, persistent disks, and accelerators (TPU). Example:

- `goog-gke-node-pool-provisioning-model`: "on-demand". Indicates the provisioning model of the node group (node pool).

NOTE: In some cases, you may need to manually add the `goog-gke-node-pool-provisioning-model` label to the descriptor when deploying the cluster, if the configuration requires it, to avoid reconciliation loops. You can also add it afterward by modifying the `KeosCluster` object. The nodes can be on-demand, reserved, or Spot.

WARNING: These automatic labels can generate a reconciliation loop in the `cluster-api-provider-gcp` (CAPG) controller in the node pools. See the xref:operations-manual:operations-manual.adoc#_reconciliation_loop_in_gke_due_to_automatic_labels[Troubleshooting] section of the operations manual for more details.

Do not edit or delete these automatic labels, since GKE automatically reconciles them when recreating nodes in the corresponding node pools.

TIP: See the official Google documentation for more information about https://docs.cloud.google.com/kubernetes-engine/docs/how-to/creating-managing-labels[automatic labels applied by GKE].

== Deployment of _aws-load-balancer-controller_ (EKS only)

In EKS clusters, a controller (_aws-load-balancer-controller_) can be deployed in charge of the creation of _Elastic Load Balancers_, used by objects such as _Ingress_ and _Service_ of type _LoadBalancer_.

Since this deployment is not enabled by default, it must be indicated in the _ClusterConfig_ resource of the cluster descriptor through `spec.eks_lb_controller: true`.

To authorize the controller, https://docs.aws.amazon.com/es_es/eks/latest/userguide/iam-roles-for-service-accounts.html[IAM roles for service accounts] will be used, which implies creating the corresponding IAM objects as indicated below:

* Define the following environment variables:
+
[source,shell]
----
export AWS_ACCOUNT_ID=<account_id>
export AWS_REGION=<aws_region>
export AWS_VPC_ID=<vpc_id>
export AWS_EKS_CLUSTER_NAME=<aws_eks_cluster_name>
export AWS_EKS_OIDC_ID=$(aws eks describe-cluster --region ${AWS_REGION} --name ${AWS_EKS_CLUSTER_NAME} --query 'cluster.identity.oidc.issuer' --output text | awk -F'/' '{print $NF}')
export AWS_IAM_POLICY_NAME="${AWS_EKS_CLUSTER_NAME}-lb-controller-manager"
export AWS_IAM_ROLE_NAME="${AWS_EKS_CLUSTER_NAME}-lb-controller-manager"
----

* https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/id_roles_create.html[Create the IAM role] that the service account of the _aws-load-balancer-controller_ deployment will use with the following trust policy:
+
[source,console]
----
$ cat << EOF > trustpolicy.json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/oidc.eks.${AWS_REGION}.amazonaws.com/id/${AWS_EKS_OIDC_ID}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.${AWS_REGION}.amazonaws.com/id/${AWS_EKS_OIDC_ID}:sub": "system:serviceaccount:kube-system:aws-load-balancer-controller",
                    "oidc.eks.${AWS_REGION}.amazonaws.com/id/${AWS_EKS_OIDC_ID}:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
EOF
$ aws iam create-role --role-name ${AWS_IAM_ROLE_NAME} --assume-role-policy-document file://trustpolicy.json
----

* https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/access_policies_create.html[Create the IAM policy] with the strictly necessary permissions:
+
[source,console]
----
$ cat << EOF > policy.json
{
	"Statement": [
		{
			"Action": [
        			"ec2:DescribeAvailabilityZones",
				"ec2:DescribeInstances",
				"ec2:DescribeSecurityGroups",
				"ec2:DescribeSubnets",
				"elasticloadbalancing:DescribeListeners",
				"elasticloadbalancing:DescribeListenerAttributes",
				"elasticloadbalancing:DescribeLoadBalancers",
				"elasticloadbalancing:DescribeLoadBalancerAttributes",
				"elasticloadbalancing:DescribeRules",
				"elasticloadbalancing:DescribeTags",
				"elasticloadbalancing:DescribeTargetGroups",
				"elasticloadbalancing:DescribeTargetGroupAttributes",
				"elasticloadbalancing:DescribeTargetHealth",
        "shield:GetSubscriptionState"
			],
			"Effect": "Allow",
			"Resource": "*"
		},
		{
			"Action": [
				"ec2:AuthorizeSecurityGroupIngress",
				"ec2:CreateSecurityGroup",
        			"ec2:CreateTags",
				"ec2:DeleteSecurityGroup",
				"ec2:RevokeSecurityGroupIngress"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:vpc/${AWS_VPC_ID}",
				"arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:security-group/*"
			]
		},
		{
			"Action": [
				"elasticloadbalancing:AddTags",
				"elasticloadbalancing:CreateListener",
				"elasticloadbalancing:CreateLoadBalancer",
				"elasticloadbalancing:CreateTargetGroup",
				"elasticloadbalancing:DeleteLoadBalancer",
				"elasticloadbalancing:DeleteTargetGroup",
				"elasticloadbalancing:DeregisterTargets",
				"elasticloadbalancing:ModifyLoadBalancerAttributes",
				"elasticloadbalancing:ModifyTargetGroup",
				"elasticloadbalancing:RegisterTargets"
			],
			"Effect": "Allow",
			"Resource": "*",
			"Condition": {
				"StringEquals": {
					"aws:ResourceTag/elbv2.k8s.aws/cluster": "${AWS_EKS_CLUSTER_NAME}"
				}
			}
		}
	],
	"Version": "2012-10-17"
}
EOF
$ aws iam create-policy --policy-name ${AWS_IAM_POLICY_NAME} --policy-document file://policy.json
----

* https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/access_policies_manage-attach-detach.html[Associate the IAM policy] with the previously created role:
+
[source,console]
----
$ aws iam attach-role-policy --role-name ${AWS_IAM_ROLE_NAME} --policy-arn arn:aws:iam::${AWS_ACCOUNT_ID}:policy/${AWS_IAM_POLICY_NAME}
----

* Restart the controller (_aws-load-balancer-controller_):
+
[source,console]
----
$ kubectl -n kube-system rollout restart deployment aws-load-balancer-controller
----
